package fibonacciChallenge;
public class Fibbonacci {
    /*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    */

	public static void main(String[] args) {
		
		long sum = 0;
		long a = 1;
		long b = 2;
		long temp = 0;
		
		while (a <= 4000000 && b <= 4000000) {
			
			if (b % 2 == 0) {
				sum += b;
			}
			temp = a;
			a = b;
			b = a + temp;
			
		}
		
		System.out.println(sum);

	}

}